spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://51.75.33.92:5432/safronov_db?currentSchema=market
    username: safronovdb
    password: 1111
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/liquibase/master.xml
server:
  port: 8189
  servlet:
    context-path: /market
jwt:
  secret: 3w2oi4urhf394ghf3497g948tyrh04283hi8wregf83w4gf8734yto34ht98h8&G*&^F7f3r87gihdsf
  lifetime: 36000000
